# permissions for end users to edit dbmanages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dbmanage-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbmanage-editor-role
rules:
- apiGroups:
  - operator.codehorse.com
  resources:
  - dbmanages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.codehorse.com
  resources:
  - dbmanages/status
  verbs:
  - get
